#!/usr/bin/env bash
# Fetch the unified diff plus the removed-lines supplement.
#
# Env in: GH_TOKEN, GITHUB_REPOSITORY, HEAD_SHA_EVENT, GITHUB_OUTPUT,
#   RUNNER_TEMP, SCRIPT_DIR. Reads muse-vars.env from collect.sh.
# Files out: muse.diff, muse-removed.txt. Output: diff_failed.
# Appends MUSE_DIFF_NOTE / MUSE_REMOVED_NOTE to muse-vars.env.
set -euo pipefail

# shellcheck disable=SC1091  # generated by collect.sh at run time
. "${RUNNER_TEMP}/muse-vars.env"
if [[ "${MUSE_STOP:-1}" == "1" ]]; then exit 0; fi
# shellcheck disable=SC1091  # SCRIPT_DIR is set by the workflow step
. "${SCRIPT_DIR}/lib.sh"

# Unified diff, truncated to a prompt budget. Collection failures are routed
# to the explicit fallback (never reviewed blind). Prefer the complete
# local merge-base diff: the Compare API caps file diffs at 300 files, so
# large PRs would otherwise review with hunks silently missing.
diff_file="${RUNNER_TEMP}/muse.diff"
if [[ "${MUSE_FILES_FAILED}" == "true" ]]; then
  diff_failed=true
elif [[ "${MUSE_FILES_SOURCE:-}" == "local" && -n "${MUSE_MERGE_BASE:-}" ]] \
  && git -c core.quotePath=false diff "${MUSE_MERGE_BASE}" "${HEAD_SHA_EVENT}" \
    > "${diff_file}" 2>"${RUNNER_TEMP}/muse-ghdiff.err"; then
  diff_failed=false
elif ! gh api -H 'Accept: application/vnd.github.diff' \
  "repos/${GITHUB_REPOSITORY}/compare/${MUSE_BASE_SHA}...${HEAD_SHA_EVENT}" \
  > "${diff_file}" 2>"${RUNNER_TEMP}/muse-ghdiff.err"; then
  diff_failed=true
else
  diff_failed=false
fi
echo "diff_failed=${diff_failed}" >> "${GITHUB_OUTPUT}"

# Removed-lines supplement, extracted from the FULL diff before any
# truncation: beyond the diff cap, deleted base-side lines would be
# invisible — the agent has no shell for `git show`, and checked-out head
# files lack them. Per-file `+++` headers attribute each `-` line; the
# sidecar has its own byte cap with an explicit marker.
removed_file="${RUNNER_TEMP}/muse-removed.txt"
removed_note=""
if [[ "${diff_failed}" != "true" ]]; then
  # Keep the diff --git and --- headers: whole-file deletions show +++
  # /dev/null, so without them removed lines lose their original path.
  awk '/^diff --git / {print} /^--- / {print} /^\+\+\+ / {print} /^-/ && !/^--- / {print}' \
    "${diff_file}" 2>/dev/null > "${removed_file}" || : > "${removed_file}"
  if (( $(wc -c < "${removed_file}") > 24576 )); then
    cap_file "${removed_file}" 24576
    removed_note=" [supplement truncated at 24576 bytes — PARTIAL]"
  fi
else
  : > "${removed_file}"
fi

budget=60000
diff_note=""
if [[ "${diff_failed}" == "true" ]]; then
  printf '(Diff collection failed; the fallback review explains. Diff error: %s)\n' \
    "$(head -c 300 "${RUNNER_TEMP}/muse-ghdiff.err" 2>/dev/null || true)" > "${diff_file}"
  diff_note=" (collection failed)"
else
  diff_len="$(wc -c < "${diff_file}")"
  if (( diff_len > budget )); then
    head -c "${budget}" "${diff_file}" > "${diff_file}.trunc"
    printf '\n[... PARTIAL DIFF truncated at %s bytes. The tail is NOT visible: read each changed file in full from the working tree, and check the <removed_lines> supplement for deleted base-side lines ...]\n' "${budget}" >> "${diff_file}.trunc"
    mv "${diff_file}.trunc" "${diff_file}"
    diff_note=" (truncated — read full files from the working tree)"
  fi
  if [[ ! -s "${diff_file}" ]]; then
    printf '(No textual diff was returned by the GitHub API.)\n' > "${diff_file}"
  fi
  if [[ "${MUSE_FILES_CAPPED:-}" == "true" ]]; then
    diff_note="${diff_note} (PARTIAL: file diff capped at 300 by the compare API)"
  fi
fi

{
  printf 'MUSE_DIFF_NOTE=%q\n' "${diff_note}"
  printf 'MUSE_REMOVED_NOTE=%q\n' "${removed_note}"
} >> "${RUNNER_TEMP}/muse-vars.env"
