#!/usr/bin/env bash
# Collect repo guidance: root candidates plus scoped AGENTS.md/CLAUDE.md from
# each changed file's ancestor dirs. Default-branch base versions are
# trusted; custom-base versions (stacked PRs, custom branches) are emitted
# from the captured base SHA labeled UNTRUSTED, as are all head fallbacks.
#
# Env in: RUNNER_TEMP, SCRIPT_DIR. Reads muse-vars.env, muse-files.json.
# Files out: muse-guidance.md. Must run from the checked-out PR head: head
# fallbacks are read from the working tree, base versions from FETCH_HEAD.
set -euo pipefail

# shellcheck disable=SC1091  # generated by collect.sh at run time
. "${RUNNER_TEMP}/muse-vars.env"
if [[ "${MUSE_STOP:-1}" == "1" ]]; then exit 0; fi
# shellcheck disable=SC1091  # SCRIPT_DIR is set by the workflow step
. "${SCRIPT_DIR}/lib.sh"

trust_base_flag="$(trust_base "${MUSE_BASE_REF}" "${MUSE_DEFAULT_BRANCH:-}" "${MUSE_BASE_AVAILABLE}")"
guidance_file="${RUNNER_TEMP}/muse-guidance.md"
: > "${guidance_file}"
guidance_bytes=0
guidance_budget=96000
guidance_cap=32000
guidance_capped=false
emit_guidance() {
  candidate="$1"
  phase="$2"
  if [[ "${guidance_capped}" == "true" ]]; then return 0; fi
  content=""
  source=""
  # Phase is pre-classified by the caller (one git show per candidate), so
  # emit only reads from its assigned source instead of probing again.
  if [[ "${phase}" == "base" ]] \
    && content="$(git show "${MUSE_BASE_SHA_FULL}:${candidate}" 2>/dev/null)"; then
    # SHA, not the branch name: branch names are submitter-controlled and
    # this label prints outside any untrusted block.
    source="trusted (base ${MUSE_BASE_SHA_FULL:0:10})"
  elif [[ "${phase}" == "xbase" ]] \
    && content="$(git show "${MUSE_BASE_SHA_FULL}:${candidate}" 2>/dev/null)"; then
    # Custom-base content from the captured SHA (never the branch name, and
    # the classifier already verified the base is available). Skip when the
    # head carries identical content — the head emission covers it — but
    # keep it when head deleted or changed the file: those base-side rules
    # still governed the change under review.
    if head_readable "${candidate}" \
      && [[ "$(cat -- "${candidate}")" == "${content}" ]]; then
      return 0
    fi
    source="UNTRUSTED (custom base ${MUSE_BASE_SHA_FULL:0:10})"
  elif [[ "${phase}" == "head" ]] && head_readable "${candidate}"; then
    # Refuse symlinks: a PR-added symlink (e.g. to /proc/self/environ, or a
    # symlinked parent dir) would otherwise embed runner secrets into the
    # prompt. The -- keeps option-like paths (e.g. --help/AGENTS.md) from
    # parsing as flags and aborting the step under set -e.
    content="$(cat -- "${candidate}")"
    source="UNTRUSTED (PR head)"
  else
    return 0
  fi
  trunc_note=""
  if (( $(printf '%s' "${content}" | wc -c) > guidance_cap )); then
    # Byte-bounded (not char-based): a multibyte file cut by chars could
    # still exceed the aggregate budget and starve later guidance.
    content="$(bound_untrusted "${content}" "${guidance_cap}")"
    trunc_note=" [TRUNCATED at ${guidance_cap} bytes]"
  fi
  # Candidate paths from changed files are submitter-controlled: flatten
  # newlines for display and omit the path from the block attribute (a quote
  # in the path would break out of it). The 300-char cut is a display label,
  # not a byte budget, so char-based slicing is correct here.
  safe_candidate="$(printf '%s' "${candidate}" | tr '\n' '_' | neutralize_tags)"
  safe_candidate="${safe_candidate:0:300}"
  # Budget the whole rendered block (heading, label, wrapper), not just
  # the content: hundreds of short files under long paths could otherwise
  # overshoot the aggregate budget severalfold with no warning.
  if [[ "${source}" == UNTRUSTED* ]]; then
    # Submitter-controlled content AND label: the candidate path derives
    # from changed files, so an instruction-like directory name would
    # otherwise place steering text beside guidance as a plain heading.
    # Keep the label inside the untrusted block with the content.
    block="$(printf '<untrusted_guidance>\n### %s (%s)%s\n\n' \
      "${safe_candidate}" "${source}" "${trunc_note}"
      printf '%s' "${content}" | iconv -c -f UTF-8 -t UTF-8 2>/dev/null \
        | neutralize_tags || true
      printf '\n</untrusted_guidance>')"
  else
    block="$(printf '\n### %s (%s)%s\n\n' "${safe_candidate}" "${source}" "${trunc_note}"
      printf '%s' "${content}" | iconv -c -f UTF-8 -t UTF-8 2>/dev/null || true
      printf '\n')"
  fi
  block_len="$(printf '%s' "${block}" | wc -c)"
  if (( guidance_bytes + block_len > guidance_budget )); then
    guidance_capped=true
    # The candidate label is submitter-controlled: reuse the sanitized,
    # capped display form so the system notice cannot carry steering text.
    printf '\n(Guidance budget exhausted at %s bytes; %s and any further scoped files omitted.)\n' \
      "${guidance_budget}" "${safe_candidate}" >> "${guidance_file}"
    return 0
  fi
  guidance_bytes=$(( guidance_bytes + block_len ))
  printf '%s\n' "${block}" >> "${guidance_file}"
}
seen_reset
for candidate in AGENTS.md CLAUDE.md CONTRIBUTING.md .github/copilot-instructions.md; do
  seen_add "${candidate}"
done
# Ancestor walk with zero subprocesses (bash prefix removal, not dirname)
# and a candidate cap: giant PRs could otherwise start tens of thousands of
# processes before the byte budget matters. Root candidates above are always
# included; the cap only trims deep scoped discovery.
candidate_cap=500
guidance_cap_hit=false
while IFS= read -r -d '' changed; do
  if (( ${#MUSE_CANDIDATES[@]} >= candidate_cap )); then
    guidance_cap_hit=true
    echo "::notice::Guidance candidate cap (${candidate_cap}) reached; deeper scoped files omitted."
    break
  fi
  if [[ "${changed}" == */* ]]; then dir="${changed%/*}"; else dir="."; fi
  # Cap enforced inside the traversal too: a single deeply nested path
  # would otherwise append two candidates per ancestor without rechecking.
  while [[ "${dir}" != "." && "${dir}" != "/" ]] && (( ${#MUSE_CANDIDATES[@]} < candidate_cap )); do
    seen_add "${dir}/AGENTS.md"
    seen_add "${dir}/CLAUDE.md"
    if [[ "${dir}" == */* ]]; then dir="${dir%/*}"; else dir="."; fi
  done
  if (( ${#MUSE_CANDIDATES[@]} >= candidate_cap )); then
    guidance_cap_hit=true
    echo "::notice::Guidance candidate cap (${candidate_cap}) reached; deeper scoped files omitted."
    break
  fi
done < <(jq -j '[.[] | .filename, (.previous_filename // empty)] | map(select(length > 0))[] + "\u0000"' "${RUNNER_TEMP}/muse-files.json" 2>/dev/null)
# Three phases: trusted base guidance first, then head versions, then
# custom-base versions — so PR-authored content can never exhaust the byte
# budget before applicable trusted rules are collected, and operative head
# rules precede superseded base context. Classified in one pass.
base_list=()
xbase_list=()
head_list=()
for candidate in "${MUSE_CANDIDATES[@]+"${MUSE_CANDIDATES[@]}"}"; do
  # Explicit base SHA, never bare FETCH_HEAD: later deepens append the head
  # to FETCH_HEAD, so the bare ref could resolve to the wrong commit.
  if [[ "${trust_base_flag}" == "true" ]] \
    && git show "${MUSE_BASE_SHA_FULL}:${candidate}" >/dev/null 2>&1; then
    base_list+=("${candidate}")
  else
    # Custom base with available content: emit its version as UNTRUSTED
    # too, so base-side rules that the PR deleted or changed are still
    # visible (emit skips it when head content is identical).
    if [[ "${MUSE_BASE_AVAILABLE:-}" == "true" && -n "${MUSE_BASE_SHA_FULL:-}" ]] \
      && git show "${MUSE_BASE_SHA_FULL}:${candidate}" >/dev/null 2>&1; then
      xbase_list+=("${candidate}")
    fi
    head_list+=("${candidate}")
  fi
done
for candidate in "${base_list[@]+"${base_list[@]}"}"; do
  emit_guidance "${candidate}" base
done
for candidate in "${head_list[@]+"${head_list[@]}"}"; do
  emit_guidance "${candidate}" head
done
for candidate in "${xbase_list[@]+"${xbase_list[@]}"}"; do
  emit_guidance "${candidate}" xbase
done
if [[ "${guidance_cap_hit}" == "true" ]]; then
  # The log notice alone is invisible to the reviewer: record the partial
  # scope in the prompt input itself so the verdict cannot silently claim
  # full coverage when scoped files were never collected.
  printf '\n(Partial scope: guidance discovery hit the %s-candidate cap; scoped files for later changed paths were omitted.)\n' \
    "${candidate_cap}" >> "${guidance_file}"
fi
if [[ ! -s "${guidance_file}" ]]; then
  printf '(No AGENTS.md, CLAUDE.md, CONTRIBUTING.md, or copilot instructions found in this repo.)\n' > "${guidance_file}"
fi
