name: CleanContactsAI
options:
  bundleIdPrefix: com.ogabassey.contactscleaner
  deploymentTarget:
    iOS: "16.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources: [iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ogabassey.contactscleaner.iosApp
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      DEVELOPMENT_TEAM: J4MXAZ4X3U
      CODE_SIGN_STYLE: Automatic
      FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../composeApp/build/xcode-frameworks"
      OTHER_LDFLAGS: "$(inherited) -framework composeApp"
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    info:
      path: iosApp/Info.plist
      properties:
        CFBundleDisplayName: "Contacts Cleaner"
        CFBundleName: "ContactsCleaner"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    preBuildScripts:
      - name: Compile Kotlin Framework
        script: |
          export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
    dependencies:
       - framework: ../composeApp/build/xcode-frameworks/composeApp.framework
         embed: false
         link: true
       - sdk: Contacts.framework
         embed: false
         link: true
